version: '3.8'

services:
  # 1. Pythonアプリの定義
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      # .envファイルから値を読み込みます
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DB=${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG}
    depends_on:
      - db

  # 2. MySQLデータベースの定義
  db:
    image: mysql:8.0
    environment:
      # .envファイルから値を読み込みます
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: